// AUTH

export const AUTH_SET = 'AUTH_SET'
export const AUTH_SET_NEW_FEED_ITEMS = 'AUTH_SET_NEW_FEED_ITEMS'
export const AUTH_SET_PLAYLISTS = 'AUTH_SET_PLAYLISTS'

export const AUTH_SET_FOLLOWINGS = 'AUTH_SET_FOLLOWINGS'
export const AUTH_SET_LIKES = 'AUTH_SET_LIKES'
export const AUTH_SET_PLAYLIST_LIKES = 'AUTH_SET_PLAYLIST_LIKES'
export const AUTH_SET_REPOSTS = 'AUTH_SET_REPOSTS'

export const AUTH_SET_LIKE = 'AUTH_SET_LIKE'
export const AUTH_SET_FOLLOWING = 'AUTH_SET_FOLLOWING'
export const AUTH_SET_REPOST = 'AUTH_SET_REPOST'

export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOADING = 'AUTH_LOADING'

// USER

export const USER_SET = 'USER_SET'
export const USER_SET_PROFILES = 'USER_SET_PROFILES'

// PLAYER

export const PLAYER_SET_TIME = 'PLAYER_SET_TIME'
export const PLAYER_UPDATE_TIME = 'PLAYER_UPDATE_TIME'
export const PLAYER_SET_DURATION = 'PLAYER_SET_DURATION'
export const PLAYER_SET_TRACK = 'PLAYER_SET_TRACK'
export const PLAYER_TOGGLE_PLAYING = 'PLAYER_TOGGLE_PLAYING'
export const PLAYER_SET_PREV_PLAYLIST = 'PLAYER_SET_PREV_PLAYLIST'
export const PLAYER_SET_PLAYLIST = 'PLAYER_SET_PLAYLIST'
export const PLAYER_QUEUE_INSERT = 'PLAYER_QUEUE_INSERT'
export const PLAYER_ADD_UP_NEXT = 'PLAYER_ADD_UP_NEXT'

// TRACKS

export const TRACK_ADD = 'TRACK_ADD'
export const TRACK_UPDATE_IMAGE = 'TRACK_UPDATE_IMAGE'
export const SET_TRACKS = 'SET_TRACKS'


// OBJECT

export const OBJECT_SET = 'OBJECT_SET'
export const OBJECT_UNSET = 'OBJECT_UNSET'
export const OBJECT_SET_TRACKS = 'OBJECT_SET_TRACKS'
export const OBJECT_UPDATE_ITEMS = 'OBJECT_UPDATE_ITEMS'

// APP

export const APP_TOGGLE_OFFLINE = 'APP_TOGGLE_OFFLINE'
export const APP_PUSH_OFFLINE_QUEUE = 'APP_PUSH_OFFLINE_QUEUE'
export const APP_POP_OFFLINE_QUEUE = 'APP_POP_OFFLINE_QUEUE'
export const APP_CLEAR_OFFLINE_QUEUE = 'APP_CLEAR_OFFLINE_QUEUE'
export const APP_SET_LOADED = 'APP_SET_LOADED'
export const APP_SET_DIMENSIONS = 'APP_SET_DIMENSIONS'
export const APP_SET_UPDATE_AVAILABLE = 'APP_SET_UPDATE_AVAILABLE'
export const APP_SET_CAN_GO = 'APP_SET_CAN_GO'

export const APP_RESET_STORE = 'APP_RESET_STORE'
export const APP_SET_SEARCH_RES = 'APP_SET_SEARCH_RES'

// CONFIG

export const CONFIG_SET_TOKEN = 'CONFIG_SET_TOKEN'
export const CONFIG_SET = 'CONFIG_SET'
export const CONFIG_SET_KEY = 'CONFIG_SET_KEY'

// SEARCH

export const SEARCH_PLAYLIST_TRACK = 'SEARCH_PLAYLIST_TRACK'

// UI

export const UI_TOGGLE_QUEUE = 'UI_TOGGLE_QUEUE'
export const UI_SET_SCROLL_TOP = 'UI_SET_SCROLL_TOP'