export const OBJECT_TYPES = {
    PLAYLISTS: "PLAYLISTS",
    CHARTS: "CHARTS",
    COMMENTS: "COMMENTS",
    USERS: "USERS",
};

export const REDUX_STATES = {
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR'
};