export const PLAYLISTS = {
    LIKES: "LIKES",
    STREAM: "STREAM",
    MYTRACKS: "MYTRACKS",
    PLAYLIST: "PLAYLIST",
    PLAYLISTS: "PLAYLISTS",

    // SEARCH
    SEARCH: "SEARCH",
    SEARCH_TRACK: "SEARCH_TRACK",
    SEARCH_USER: "SEARCH_USER",
    SEARCH_PLAYLIST: "SEARCH_PLAYLIST",
};

export const RELATED_PLAYLIST_SUFFIX = "_RELATED";
export const USER_TRACKS_PLAYLIST_SUFFIX = "_TRACKS";
export const USER_LIKES_SUFFIX = "_LIKED";

export const SEARCH_TRACKS_SUFFIX = "_SEARCH_TRACKS";
export const SEARCH_USERS_SUFFIX = "_SEARCH_USERS_SUFFIX";
export const SEARCH_TRACKS_PLAYLISTS_SUFFIX = "_SEARCH_TRACKS_PLAYLISTS";
export const SEARCH_PLAYLISTS_SUFFIX = "_SEARCH_PLAYLISTS";
export const SEARCH_SUFFIX = "_SEARCH";
