export const PLAYLISTS = {
    LIKES: "LIKES",
    STREAM: "STREAM",
    MYTRACKS: "MYTRACKS",
    PLAYLIST: "PLAYLIST",
    PLAYLISTS: "PLAYLISTS",

    // SEARCH
    SEARCH: "SEARCH",
    SEARCH_TRACK: "SEARCH_TRACK",
    SEARCH_USER: "SEARCH_USER",
    SEARCH_PLAYLIST: "SEARCH_PLAYLIST",
};
